# Generated by Django 4.2.5 on 2023-09-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
