# Generated by Django 4.2.5 on 2023-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2012-01-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
