# Generated by Django 4.2.5 on 2023-09-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_booking_date_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
