# Generated by Django 4.2.5 on 2023-09-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
