# Generated by Django 4.2.5 on 2023-09-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_rename_sender_messages_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver_id',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
