# Generated by Django 4.2.5 on 2023-09-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_messages_receiver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
