# Generated by Django 4.2.5 on 2023-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_receiver_id_messages_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
