# Generated by Django 4.2.5 on 2023-09-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
