# Generated by Django 4.2.5 on 2023-09-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_booking_booking_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
