# Generated by Django 4.2.5 on 2024-06-23 06:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_capacity', models.IntegerField()),
                ('location', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Gujrat', 'Gujrat'), ('Madhya pradesh', 'Madhya pradesh'), ('Maharastra', 'Maharastra')], max_length=50)),
                ('service_offered', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField()),
                ('category', models.ManyToManyField(to='EventPlanner.category')),
                ('vendors', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('venue_images', models.ManyToManyField(blank=True, null=True, to='EventPlanner.image')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('is_customer', 'is_customer'), ('is_event_planner', 'is_event_planner')], max_length=50)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact information')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('location', models.TextField(blank=True, null=True)),
                ('service_offered', models.TextField(blank=True, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('otp_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_images', models.ManyToManyField(blank=True, null=True, related_name='portfolio_images', to='EventPlanner.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.userprofile'),
        ),
        migrations.AddField(
            model_name='image',
            name='venue_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.venue'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.category')),
                ('event_planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
