# Generated by Django 4.2.5 on 2024-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_verified',
            field=models.BooleanField(default=True),
        ),
    ]
