# Generated by Django 4.2.5 on 2023-09-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0004_userprofile_bio_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
