# Generated by Django 4.2.5 on 2023-09-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0005_alter_userprofile_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
