# Generated by Django 4.2.5 on 2023-09-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0007_remove_userprofile_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_offered_new',
            field=models.TextField(blank=True, null=True),
        ),
    ]
