# Generated by Django 4.2.5 on 2023-09-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0008_userprofile_service_offered_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='service_offered_new',
        ),
    ]
