# Generated by Django 4.2.5 on 2023-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0009_remove_userprofile_service_offered_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('is_customer', 'customer'), ('is_event_planner', 'Event planner')], default='is_customer', max_length=50),
            preserve_default=False,
        ),
    ]
