# Generated by Django 4.2.5 on 2023-10-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0010_userprofile_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_verified',
        ),
    ]
