# Generated by Django 4.2.5 on 2023-09-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0010_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('is_customer', 'is_customer'), ('is_event_planner', 'is_event_planner')], max_length=50),
        ),
    ]
