# Generated by Django 4.2.5 on 2023-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0013_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.TextField(default='not yet'),
            preserve_default=False,
        ),
    ]
