# Generated by Django 4.2.5 on 2023-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0014_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='service_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
