# Generated by Django 4.2.5 on 2023-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0015_alter_venue_service_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.ManyToManyField(to='EventPlanner.category'),
        ),
    ]
