# Generated by Django 4.2.5 on 2023-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0016_venue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='not yet', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
