# Generated by Django 4.2.5 on 2023-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0017_userprofile_city_alter_venue_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
