# Generated by Django 4.2.5 on 2023-09-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0018_venue_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='price',
            new_name='min_price',
        ),
    ]
