# Generated by Django 4.2.5 on 2023-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0019_rename_price_venue_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
