# Generated by Django 4.2.5 on 2023-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0021_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='gujrat', max_length=20),
            preserve_default=False,
        ),
    ]
