# Generated by Django 4.2.5 on 2023-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0022_alter_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='max_capacity',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
