# Generated by Django 4.2.5 on 2023-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0023_venue_max_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='about',
        ),
        migrations.AddField(
            model_name='venue',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
