# Generated by Django 4.2.5 on 2023-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0024_rename_bio_userprofile_about_venue_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_info',
            field=models.TextField(default='@gmail.com'),
            preserve_default=False,
        ),
    ]
