# Generated by Django 4.2.5 on 2023-09-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0025_venue_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
