# Generated by Django 4.2.5 on 2023-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0026_remove_event_event_date_time_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
