# Generated by Django 4.2.5 on 2023-10-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0031_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_images',
            field=models.ManyToManyField(blank=True, null=True, to='EventPlanner.image'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_images',
            field=models.ManyToManyField(blank=True, null=True, to='EventPlanner.image'),
        ),
    ]
