# Generated by Django 4.2.5 on 2023-10-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0032_image_userprofile_vendor_images_venue_venue_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='venue_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.venue'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.userprofile'),
        ),
    ]
