# Generated by Django 4.2.5 on 2023-10-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0033_image_venue_object_alter_image_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='showcase_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.userprofile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='venue_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventPlanner.venue'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vendor_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='portfolio_images', to='EventPlanner.image'),
        ),
    ]
