# Generated by Django 4.2.5 on 2023-10-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventPlanner', '0034_userprofile_showcase_image_alter_image_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='showcase_image',
        ),
    ]
